name: Trigger auto deployment for filemanager

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/filemanager-AutoDeployTrigger-55e5657d-8fe7-471d-a69c-2bc93cdccc5c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FILEMANAGER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FILEMANAGER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FILEMANAGER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: filemanagerregister.azurecr.io
          registryUsername: ${{ secrets.FILEMANAGER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FILEMANAGER_REGISTRY_PASSWORD }}
          containerAppName: filemanager
          resourceGroup: spring-filemanager
          imageToBuild: filemanagerregister.azurecr.io/filemanager:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


